### ISSUE TITLE
关于data_bert_trunk方法中，375的计算方式

### ISSUE THREAD

**Issue by lc0370** [zhoucz97/ECPE-MM-R#1]
我想使用英文数据集在您的工作上运行，但是处理好数据集后报出了很多错误，阅读代码后发现这个地方不是特别理解，希望您能抽时间帮忙解答一下！
makeData_Dual.py中data_bert_trunk方法：
`if sum_len > 375:  # trunk
        # 375是根据数据集的特点事先算好的，只要总文档长度不大于375，那么加上query就能小于512`

**Comment by zhoucz97** [comment]
因为bert接受的序列输入最长是512，而MM-R中输入的格式是`[query, document]` ，所以要保证`len(query+document+special_tokens)`不大于512，我事先算出了数据集中query长度的最大值（假设为N），把所有的document都截断到小于等于`512-N-len(special_tokens)`的长度，发现document小于375时是满足的。

总结来说就是送到BERT的输入不能大于512，至于怎么截断query和document，自己决定就行。

**Comment by lc0370** [comment]
非常感谢您的解答！
