### ISSUE TITLE
关于数据划分方式

### ISSUE THREAD

**Issue by Hui-design** [zhoucz97/ECPE-MM-R#2]
作者您好！
在main.py中使用的是10-fold的划分方式，我如何改成Training/Validation/Test data set的方式？

**Comment by zhoucz97** [comment]
您好，main.py中只提供了十折交叉验证的代码，Train/Valid/Test数据集划分需要您自行修改。Train/Valid/Test数据集划分我们参考的是论文《Transition-based Directed Graph Construction for Emotion-Cause Pair Extraction》的划分方式，您可以去他的github repo中看一下数据集及代码实现：https://github.com/HLT-HITSZ/TransECPE

**Comment by Hui-design** [comment]
谢谢！
